stages:
  - lint
  - build
  - upload

variables:
  UPLOAD_URL_BASE: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_PROJECT_NAME}/${CI_COMMIT_TAG}"
  BUILD_RELEASE: "build-release"
  MESON_DIST: "${BUILD_RELEASE}/meson-dist"
  MESON_NAME: "tubefeeder"
  RUSTFLAGS: "-Dwarnings"

build:
  stage: build
  image: archlinux:base-devel
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - env
    - pacman -Syu rustup meson gtk4 git cmake libadwaita blueprint-compiler --noconfirm
    - rustup default stable
    - meson setup $BUILD_RELEASE
    - meson dist -C $BUILD_RELEASE
    - ls $MESON_DIST
  artifacts:
    paths:
      - ${MESON_DIST}/${MESON_NAME}-${CI_COMMIT_TAG:1}.tar.xz
      - ${MESON_DIST}/${MESON_NAME}-${CI_COMMIT_TAG:1}.tar.xz.sha256sum
    expire_in: 1 week


upload:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${MESON_DIST}/${MESON_NAME}-${CI_COMMIT_TAG:1}.tar.xz "${UPLOAD_URL_BASE}/${MESON_NAME}-${CI_COMMIT_TAG:1}.tar.xz"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ${MESON_DIST}/${MESON_NAME}-${CI_COMMIT_TAG:1}.tar.xz.sha256sum "${UPLOAD_URL_BASE}/${MESON_NAME}-${CI_COMMIT_TAG:1}.tar.xz.sha256sum"'

test:cargo-deny:
  stage: lint
  image: archlinux:base-devel
  script:
    - pacman -Syu rustup cargo-deny --noconfirm
    - rustup default stable
    - cargo deny check
  allow_failure: true


test:cargo-fmt:
  stage: lint
  image: archlinux:base-devel
  script:
    - pacman -Syu rustup meson gtk4 git cmake libadwaita  blueprint-compiler --noconfirm
    - rustup default stable
    - rustup component add rustfmt
    - meson setup build
    - meson compile -C build resources_gresource
    - cargo fmt -- --check
  allow_failure: true

test:cargo-clippy:
  stage: lint
  image: archlinux:base-devel
  script:
    - pacman -Syu rustup meson gtk4 git cmake libadwaita  blueprint-compiler --noconfirm
    - rustup default stable
    - rustup component add clippy
    - meson setup build
    - meson compile -C build resources_gresource
    - cargo clippy --verbose
  allow_failure: true

