[package]
name = "tubefeeder"
description = "Watch YouTube, LBRY, and PeerTube videos in one place"
homepage = "https://mobile.schmidhuberj.de/pipeline"
repository = "https://gitlab.com/schmiddi-on-mobile/pipeline"
version = "1.13.0"
authors = ["Julian Schmidhuber <schmidhuberj2@protonmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.6.6", package = "gtk4", features = ["v4_10"] }
gdk-pixbuf = "0.17.10"
gdk = { version = "0.6.3", package = "gdk4" }
pango = "0.15.10"
libadwaita = { version = "0.4.4", features = ["v1_2"]}

tokio = {version = "1.29.1", features = ["full"]}
futures = "0.3.28"
regex = "1.9.1"
chrono = { version = "0.4.26" }
csv = "1.2.2"
reqwest = "0.11.18"

log = "0.4.19"
env_logger = "0.9.3"

image = "0.24.6"
once_cell = "1.18.0"

gettext-rs = "0.7.0"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

tf_core = { git = "https://gitlab.com/schmiddi-on-mobile/tubefeeder-extractor.git", rev = "98c9b2d03bb7b9329b1b2cb561b6709e26980305" }
tf_join = { git = "https://gitlab.com/schmiddi-on-mobile/tubefeeder-extractor.git", rev = "98c9b2d03bb7b9329b1b2cb561b6709e26980305" }
tf_filter = { git = "https://gitlab.com/schmiddi-on-mobile/tubefeeder-extractor.git", rev = "98c9b2d03bb7b9329b1b2cb561b6709e26980305" }
tf_observer = { git = "https://gitlab.com/schmiddi-on-mobile/tubefeeder-extractor.git", rev = "98c9b2d03bb7b9329b1b2cb561b6709e26980305" }
tf_playlist = { git = "https://gitlab.com/schmiddi-on-mobile/tubefeeder-extractor.git", rev = "98c9b2d03bb7b9329b1b2cb561b6709e26980305" }
tf_yt = { package = "tf_platform_youtube", git = "https://gitlab.com/schmiddi-on-mobile/tubefeeder-extractor.git", rev = "98c9b2d03bb7b9329b1b2cb561b6709e26980305"  }
tf_pt = { package = "tf_platform_peertube", git = "https://gitlab.com/schmiddi-on-mobile/tubefeeder-extractor.git", rev = "98c9b2d03bb7b9329b1b2cb561b6709e26980305"  }
