[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "ISC",
    "Unicode-DFS-2016",
    "OpenSSL",
    "BSD-3-Clause"
]
copyleft = "allow"

[[licenses.clarify]]
name = "ring"
expression = "ISC AND OpenSSL AND MIT"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[bans]
multiple-versions = "allow"

[sources.allow-org]
gitlab = ["schmiddi-on-mobile"]
